---
title: "Day 1 EOD activity"
format: html
editor: visual
---

## 2. Data import and exploration 


```{r}
# load in packages ----
library(tidyverse)
library(janitor)
```

```{r}
# read in the data ----
stl_blood_lead <- read_csv(here::here("data", "stl_blood_lead.csv"),)

# cleaning names
stl_blood_lead <- clean_names(stl_blood_lead)

# exploring the data 

skimr::skim(stl_blood_lead)
names(stl_blood_lead)
dim(stl_blood_lead)

```


```{r}
# creating a new data frame 
stl_lead_prop <- stl_blood_lead %>% dplyr::mutate(prop_white = white / total_pop * 100)

#looking to see if it now has an additional column 
dim(stl_lead_prop) 
#it now has 16 columns! 
```

## Visualize data 


```{r}
# creating a scatter plot ----
# percent of children 'pct_elevated' versus the percent of each census identifying as white 'white'

stl_lead_plot <- ggplot(data = stl_lead_prop,
               aes(x = pct_elevated,
                   y = prop_white)) +
  geom_point(aes(color = prop_white), size = 4, show.legend = FALSE) +
  theme_classic() +
  scale_color_gradient(low = "lightpink", high = "darkred") +
  labs(x = "% of children with elevated blood lead levels",
       y = "% of census that identifies as white",
       title = "Elevated Blood Lead Levels in Census Tract")

stl_lead_plot
```

In this scatterplot, there is an overall trend of less children with elevated blood lead in the census tracts with a higher % of white individuals. 

```{r}
# saving our plot as a png ----
ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```


```{r}
# creating histogram ----
pct_elevated_hist<- ggplot(data = stl_lead_prop, 
                           aes(x = pct_elevated))+
  geom_histogram(fill = "cadetblue2", colour = "cadetblue", show.legend = FALSE)+
  labs(x ="% of children with elevated blood lead levels",
       y = "Count",
       title = "Count of children with elevated lead blood levels")

pct_elevated_hist

# saving as a jpeg

ggsave(here::here("figs", "pct_elevated_hist.jpeg"), height = 6, width = 5)
```

